from pathlib import Path
p=Path('app/src/main/java/com/alpvz/gardendefense/MainActivity.java')
s=p.read_text(encoding='utf-8')
def r(a,b):
 global s
 if s.count(a)!=1: raise SystemExit('replace count '+str(s.count(a))+' for '+a[:40])
 s=s.replace(a,b,1)
r('getWidth() * .465f,\n                    getHeight() * .075f,\n                    getWidth() * .525f,\n                    getHeight() * .15f,','getWidth() * .82f,\n                    getHeight() * .075f,\n                    getWidth() * .87f,\n                    getHeight() * .15f,')
r('getWidth() * .495f,\n                    getHeight() * .122f,','getWidth() * .845f,\n                    getHeight() * .122f,')
if 'inside(x, y, .465f, .075f, .525f, .15f)' in s:r('inside(x, y, .465f, .075f, .525f, .15f)','inside(x, y, .82f, .075f, .87f, .15f)')
if 'float binuTargetX = 0f;' not in s:r('boolean binuSound1Finished = false;\n\n        MediaPlayer binuSound1Player;','boolean binuSound1Finished = false;\n        float binuX=0f,binuY=0f,binuStartX=0f,binuStartY=0f,binuTargetX=0f,binuTargetY=0f;\n\n        MediaPlayer binuSound1Player;')
start=s.index('        private void drawBinu(Canvas c) {'); end=s.index('        private void playBinuSound1()',start)
s=s[:start]+'''        private void drawBinu(Canvas c) {\n            if (!binuWaiting && !binuJumping) return;\n            if (binuRow < 0 || binuCol < 0) return;\n            Bitmap b=binuImg;\n            if (binuJumping) { if (binuFrame==1) b=binu1Img; else if (binuFrame==2) b=binu2Img; else if (binuFrame==3) b=binu3Img; else if (binuFrame>=4) b=binu4Img; }\n            if (b==null) return;\n            float x=binuJumping?binuX:left+binuCol*cellW+cellW/2f; float y=binuJumping?binuY:top+binuRow*cellH+cellH/2f;\n            c.drawBitmap(b,null,new RectF(x-cellW*.37f,y-cellH*.42f,x+cellW*.37f,y+cellH*.42f),p);\n        }\n\n'''+s[end:]
m='Plant plant = plants[r][col];\n                    if (plant == null) continue;'
if 'if (plant.type == BINU && binuWaiting) continue;' not in s:r(m,m+'\n                    if (plant.type == BINU && binuWaiting) continue;')
start=s.index('        private void updateBinu(long now) {'); end=s.index('        private void updatePeas(float dt) {',start)
s=s[:start]+'''        private void updateBinu(long now) {\n            if (binuWaiting && !binuJumping && now>=binuDetectAt && binuSound1Finished) startBinuJump(now);\n            if (!binuJumping) return;\n            long e=now-binuClock; float t=Math.max(0f,Math.min(1f,e/480f)); float q=t*t*(3f-2f*t);\n            binuX=binuStartX+(binuTargetX-binuStartX)*q; binuY=binuStartY+(binuTargetY-binuStartY)*q; binuFrame=Math.max(1,Math.min(4,(int)(e/120L)+1));\n            if(e>=480L){binuX=binuTargetX;binuY=binuTargetY;smashBinu();binuJumping=false;binuWaiting=false;binuFrame=0;binuRow=-1;binuCol=-1;}\n        }\n        private void checkBinu(long now) {\n            if(binuWaiting||binuJumping)return;\n            for(int r=0;r<ROWS;r++)for(int c=0;c<COLS;c++){Plant a=plants[r][c];if(a==null||a.type!=BINU)continue;float bx=left+c*cellW+cellW/2f;for(Zombie z:zombies)if(z.hp>0&&z.row==r&&z.x>bx&&z.x<=bx+cellW*1.30f){binuRow=r;binuCol=c;binuWaiting=true;binuDetectAt=now+2000L;binuX=bx;binuY=top+r*cellH+cellH/2f;return;}}\n        }\n        private void startBinuJump(long now) {\n            if(!binuWaiting||binuRow<0||binuCol<0)return; float sx=left+binuCol*cellW+cellW/2f,sy=top+binuRow*cellH+cellH/2f; Zombie target=null;float best=Float.MAX_VALUE;\n            for(Zombie z:zombies)if(z.hp>0&&z.row==binuRow&&z.x>=sx){float d=z.x-sx;if(d<=cellW*1.80f&&d<best){target=z;best=d;}}\n            if(target==null){binuWaiting=false;return;} binuStartX=sx;binuStartY=sy;binuTargetX=target.x;binuTargetY=target.y;binuX=sx;binuY=sy;plants[binuRow][binuCol]=null;binuJumping=true;binuFrame=1;binuClock=now;playBinuSound2();\n        }\n        private void smashBinu() {\n            if(binuRow<0)return; float cx=binuTargetX,range=cellW*1.25f; for(Zombie z:zombies)if(z.hp>0&&z.row==binuRow&&Math.abs(z.x-cx)<=range){if(z.boss)z.hp=Math.max(1f,z.hp*.50f);else z.hp=0;}\n        }\n\n'''+s[end:]
start=s.index('        private void usePlantFood(Plant a) {'); end=s.index('        private void drawOverlay(',start)
s=s[:start]+'''        private void usePlantFood(Plant a) {\n            if(a==null||a.type==BINU||a.foodUsed||food<=0)return; long now=System.currentTimeMillis(); food--; a.foodUsed=true; playPlantFoodSound();\n            if(a.type==GIGANUT){a.maxHp=8000;a.hp=8000;a.plantFoodUntil=Long.MAX_VALUE;}\n            else if(a.type==SUNFLOWER){a.plantFoodUntil=now+5000L;a.last=now-2000L;}\n            else if(a.type==PEASHOOTER||a.type==REPEATER){a.plantFoodUntil=now+5000L;a.last=now-1000L;for(Zombie z:zombies)if(z.row==a.row&&!z.boss&&z.hp>0)z.hp=Math.max(0f,z.hp*(2f/3f));}\n            else if(a.type==CHOMPER){Zombie z=nearestZombie(a.row,a.col,cellW*2f);if(z!=null&&!z.boss)z.hp=0;}\n            else if(a.type==MINE){for(Zombie z:zombies)if(z.row==a.row&&!z.boss&&Math.abs(z.x-(left+a.col*cellW+cellW/2f))<cellW*2.2f)z.hp=Math.max(0f,z.hp-1800f);a.hp=0;}\n        }\n\n'''+s[end:]
old='usePlantFood(plants[row][col]);\n                        food--;'
if old in s:r(old,'usePlantFood(plants[row][col]);')
if 'fireDelayed(r, col, 30, 250);' in s:r('fireDelayed(r, col, 30, 250);','fireDelayed(r, col, 30, 500);')
if 'a.animFrame = 1;' in s:r('''                        if (a.animFrame > 10) {\n                            a.animFrame = 1;\n                        }''','''                        if (a.animFrame > 10) {\n                            a.animFrame = 0;\n                        }''')
if 'private int activeRows()' not in s:r('        private long spawnDelay() {','''        private int activeRows(){if(level==1)return 1;if(level<=3)return 3;return 5;}\n        private boolean activeRow(int row){int n=activeRows(),first=(ROWS-n)/2;return row>=first&&row<first+n;}\n\n        private long spawnDelay() {''')
r('int row = random.nextInt(ROWS);\n\n            boolean boss =','int n=activeRows(),first=(ROWS-n)/2;\n            int row=first+random.nextInt(n);\n\n            boolean boss =')
board='''                    p.setColor(\n                            (r + col) % 2 == 0\n                                    ? Color.rgb(103, 166, 78)\n                                    : Color.rgb(91, 153, 67)\n                    );'''
if board in s:r(board,'''                    if(!activeRow(r))p.setColor(Color.rgb(72,110,62));\n                    else p.setColor((r+col)%2==0?Color.rgb(103,166,78):Color.rgb(91,153,67));''')
mark='''                if (row < 0 || row >= ROWS ||\n                        col < 0 || col >= COLS) {\n                    return true;\n                }\n\n                if (tool == TOOL_SHOVEL) {'''
if mark in s:r(mark,'''                if (row < 0 || row >= ROWS ||\n                        col < 0 || col >= COLS) {\n                    return true;\n                }\n                if(!activeRow(row))return true;\n\n                if (tool == TOOL_SHOVEL) {''')
r('speed = cellW * .08f;\n                    damage = 45;','speed = cellW * .0533f;\n                    damage = 45;')
r('speed = cellW * .12f;','speed = cellW * .08f;')
r('speed = cellW * .30f;','speed = cellW * .20f;')
r('speed = cellW * .19f;','speed = cellW * .1267f;')
start=s.index('        private void drawMowers(Canvas c) {'); end=s.index('        private void drawHp(',start)
s=s[:start]+'''        private void drawMowers(Canvas c) {\n            for(Mower m:mowers){float y=top+m.row*cellH+cellH*.72f,L=m.x-cellW*.26f,R=m.x+cellW*.26f,T=y-cellH*.17f,wr=Math.max(3f,cellH*.045f);p.setColor(m.used?Color.DKGRAY:Color.rgb(75,125,75));c.drawRoundRect(L,T,R,y,8,8,p);p.setColor(Color.DKGRAY);c.drawCircle(L+cellW*.10f,y+wr,wr,p);c.drawCircle(R-cellW*.10f,y+wr,wr,p);p.setStrokeWidth(Math.max(3f,cellW*.025f));c.drawLine(R-cellW*.04f,T,R+cellW*.18f,T-cellH*.27f,p);c.drawLine(R+cellW*.18f,T-cellH*.27f,R+cellW*.28f,T-cellH*.27f,p);}\n        }\n\n'''+s[end:]
if 'binuTargetX = binuTargetY = 0f;' not in s:r('binuSound1Finished = false;\n            stopBinuSound1();','binuSound1Finished = false;\n            binuX=binuY=binuStartX=binuStartY=binuTargetX=binuTargetY=0f;\n            stopBinuSound1();')
for x in ['activeRows()','activeRow(int row)','binuTargetX','elapsed >= 480L','z.hp * (2f / 3f)','m.x += cellW * 17f * dt']:
 if x not in s: raise SystemExit('missing '+x)
if any(x in s.lower() for x in ['conveyor','minigame','zen garden','zomvinhhung']): raise SystemExit('removed feature returned')
if s.count('private void updatePlants(long now) {')!=1 or s.count('private void updateZombies(long now, float dt) {')!=1:raise SystemExit('duplicate method')
if s.count('{')!=s.count('}'):raise SystemExit('brace imbalance')
if s.count('food--;')!=1:raise SystemExit('food decrement')
p.write_text(s,encoding='utf-8')
print('validated',len(s))
