package com.alpvz.tankadventures;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.ActivityInfo;import android.graphics.*;import android.view.*;import java.util.*;
public class MainActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);setContentView(new V(this));}
 static class V extends View{
  Paint p=new Paint(1); Random r=new Random(); android.content.SharedPreferences sp;
  int[] hp={500,800,1100,1500},dmg={60,95,135,180},cost={0,1000,2000,3000}; float[] speed={3.6f,3.9f,4.2f,4.5f}; String[] name={"Scout","Panzer","Tiger","Titan"};
  int coins,open,wins,owned,sel,level=1,php,spawn,dead; long start,lastFire,lastSpawn,lastCrate,bigUntil; boolean menu=true,shop,levels,play,win,lose,mt,at; float px,py,vx,vy,ang,jx,jy,kx,ky,ax,ay,akx,aky;
  ArrayList<E> es=new ArrayList<>();ArrayList<B> bs=new ArrayList<>();ArrayList<C> cs=new ArrayList<>();
  V(Context c){super(c);sp=c.getSharedPreferences("ta",0);coins=sp.getInt("coins",0);open=Math.max(1,Math.min(15,sp.getInt("open",1)));wins=sp.getInt("wins",0);owned=Math.max(0,Math.min(3,sp.getInt("owned",0)));sel=Math.max(0,Math.min(owned,sp.getInt("sel",0)));p.setTypeface(Typeface.DEFAULT_BOLD);}
  void save(){sp.edit().putInt("coins",coins).putInt("open",open).putInt("wins",wins).putInt("owned",owned).putInt("sel",sel).apply();}
  protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();if(play){upd();battle(c,w,h);}else{bg(c,w,h);if(win||lose){objects(c);result(c,w,h);}else if(shop)shop(c,w,h);else if(levels)levels(c,w,h);else menu(c,w,h);}postInvalidateDelayed(16);}
  void bg(Canvas c,int w,int h){c.drawColor(Color.rgb(74,92,67));p.setColor(Color.rgb(94,92,75));for(int x=0;x<w;x+=72)for(int y=0;y<h;y+=72)c.drawRect(x+2,y+2,x+69,y+69,p);p.setColor(Color.rgb(126,119,89));c.drawRect(0,0,58,h,p);txt(c,"BASE",29,h/2f,13,Color.WHITE,true,true);}
  void menu(Canvas c,int w,int h){txt(c,"TANK ADVENTURES",w/2,55,38,Color.WHITE,true,true);txt(c,"Xu: "+coins+"   Xe: "+name[sel],w/2,92,19,Color.WHITE,true,true);txt(c,"Màn mở: "+open+"/15",w/2,120,17,Color.WHITE,true,true);btn(c,w/2-150,150,w/2+150,205,"CHƠI MÀN "+level);btn(c,w/2-150,220,w/2+150,275,"CHỌN MÀN");btn(c,w/2-150,290,w/2+150,345,"CỬA HÀNG");txt(c,"Mỗi màn phải thắng 2 lần mới mở màn tiếp theo.",w/2,h-25,15,Color.WHITE,true,true);}
  void shop(Canvas c,int w,int h){txt(c,"CỬA HÀNG XE TĂNG",w/2,38,29,Color.WHITE,true,true);txt(c,"Xu: "+coins,w/2,65,18,Color.WHITE,true,true);for(int i=0;i<4;i++){float x=100+i*180; tank(c,x,145,i,1);txt(c,name[i],x,220,17,Color.WHITE,true,true);txt(c,"HP "+hp[i]+"  DMG "+dmg[i],x,243,13,Color.WHITE,true,true);String s=owned>=i?(sel==i?"ĐANG DÙNG":"DÙNG"):"MUA "+cost[i];btn(c,x-65,262,x+65,310,s);}btn(c,20,h-52,145,h-12,"QUAY LẠI");}
  void levels(Canvas c,int w,int h){txt(c,"CHỌN MÀN",w/2,38,29,Color.WHITE,true,true);for(int i=1;i<=15;i++){int z=i-1,col=z%5,row=z/5;float x=100+col*155,y=75+row*82;btn(c,x-48,y,x+48,y+48,i<=open?""+i:"LOCK");}txt(c,"60 giây • 15 xe địch",w/2,h-25,15,Color.WHITE,true,true);btn(c,20,h-52,145,h-12,"QUAY LẠI");}
  void battle(Canvas c,int w,int h){bg(c,w,h);objects(c);p.setColor(Color.argb(210,0,0,0));c.drawRect(0,0,w,45,p);txtL(c,"MÀN "+level+" | ĐỊCH "+dead+"/15",12,30,16,Color.WHITE);txtR(c,"HP "+php+"/"+hp[sel],w-10,20,14,Color.WHITE);int sec=(int)Math.max(0,(60000-(System.currentTimeMillis()-start)+999)/1000);txtR(c,"TIME "+sec+"s",w-10,39,13,Color.WHITE);p.setColor(Color.DKGRAY);c.drawRect(285,7,450,17,p);p.setColor(Color.GREEN);c.drawRect(285,7,285+165*Math.max(0,Math.min(1,php/(float)hp[sel])),17,p);joy(c,105,h-90,true);joy(c,w-105,h-90,false);}
  void joy(Canvas c,float x,float y,boolean move){p.setColor(Color.argb(90,0,0,0));c.drawCircle(x,y,70,p);p.setColor(Color.argb(150,220,220,220));float qx=move?(mt?kx:x):(at?akx:x),qy=move?(mt?ky:y):(at?aky:y);c.drawCircle(qx,qy,27,p);if(!move)txt(c,"BẮN",x,y+5,15,Color.WHITE,true,true);}
  void objects(Canvas c){for(E e:es){tank(c,e.x,e.y,e.boss?3:1,1);p.setColor(Color.DKGRAY);c.drawRect(e.x-25,e.y-35,e.x+25,e.y-30,p);p.setColor(Color.RED);c.drawRect(e.x-25,e.y-35,e.x-25+50*e.hp/(float)e.max,e.y-30,p);}tank(c,px,py,sel,1);for(B b:bs){p.setColor(b.big?Color.YELLOW:Color.CYAN);c.drawCircle(b.x,b.y,b.big?10:6,p);}for(C z:cs){p.setColor(z.type==0?Color.GREEN:Color.MAGENTA);c.drawRect(z.x-15,z.y-15,z.x+15,z.y+15,p);txt(c,z.type==0?"HP":"BIG",z.x,z.y+5,9,Color.WHITE,true,true);}}
  void tank(Canvas c,float x,float y,int t,float sc){p.setColor(t==0?Color.GREEN:(t==1?Color.rgb(70,110,70):t==2?Color.rgb(45,95,55):Color.rgb(25,70,35)));c.drawRoundRect(x-28*sc,y-20*sc,x+28*sc,y+20*sc,8,8,p);p.setColor(Color.DKGRAY);c.drawRect(x-6*sc,y-27*sc,x+6*sc,y+27*sc,p);p.setColor(Color.rgb(40,40,40));c.drawRect(x,y-4*sc,x+30*sc,y+4*sc,p);}
  void upd(){long now=System.currentTimeMillis();float dx=mt?(kx-jx)/60:0,dy=mt?(ky-jy)/60:0;float a=.16f;vx+=dx*speed[sel]*a;vy+=dy*speed[sel]*a;float lim=speed[sel];vx=Math.max(-lim,Math.min(lim,vx));vy=Math.max(-lim,Math.min(lim,vy));if(!mt){vx*=.92f;vy*=.92f;}px=Math.max(70,Math.min(getWidth()-70,px+vx));py=Math.max(70,Math.min(getHeight()-70,py+vy));if(at){float qx=akx-ax,qy=aky-ay;if(Math.hypot(qx,qy)>8)ang=(float)Math.atan2(qy,qx);}if(now-lastFire>=3000){lastFire=now;bs.add(new B(px+(float)Math.cos(ang)*28,py+(float)Math.sin(ang)*28,(float)Math.cos(ang)*8,(float)Math.sin(ang)*8,true,now<bigUntil,dmg[sel]));}if(spawn<15&&now-lastSpawn>=2000){lastSpawn=now;E e=new E();e.boss=level==15&&spawn==14;e.max=e.hp=e.boss?hp[sel]+150:200;e.x=getWidth()-50;e.y=80+r.nextFloat()*(getHeight()-160);e.sp=speed[sel]*.58f;e.lastShot=now;es.add(e);spawn++;}if(now-lastCrate>=7000){lastCrate=now;C z=new C();z.type=r.nextInt(2);z.x=80+r.nextFloat()*(getWidth()-160);z.y=70+r.nextFloat()*(getHeight()-140);cs.add(z);}for(E e:es){if(e.boss){if(now-e.lastShot>=3000){e.lastShot=now;shoot(e);}continue;}float edx=px-e.x,edy=py-e.y,d=(float)Math.hypot(edx,edy);if(d>85){e.x+=edx/d*e.sp;e.y+=edy/d*e.sp;}else if(now-e.lastShot>=1000){e.lastShot=now;php-=25;}if(now-e.lastShot>=3000){e.lastShot=now;shoot(e);}}Iterator<B> ib=bs.iterator();while(ib.hasNext()){B b=ib.next();b.x+=b.vx;b.y+=b.vy;boolean hit=false;if(b.player){for(E e:es)if(distance(b.x,b.y,e.x,e.y)<30+(b.big?10:0)){e.hp-=b.damage;hit=true;break;}}else if(distance(b.x,b.y,px,py)<28){php-=35;hit=true;}if(hit||b.x<50||b.x>getWidth()+50||b.y<-50||b.y>getHeight()+50)ib.remove();}Iterator<E> ie=es.iterator();while(ie.hasNext()){E e=ie.next();if(e.hp<=0){ie.remove();dead++;}}Iterator<C> ic=cs.iterator();while(ic.hasNext()){C z=ic.next();if(distance(z.x,z.y,px,py)<45){if(z.type==0)php=hp[sel];else bigUntil=now+60000;ic.remove();}}if(php<=0){play=false;win=false;lose=true;save();}else if(dead>=15){play=false;win=true;lose=false;coins+=100;wins++;if(wins>=2&&level<15){open=Math.max(open,level+1);wins=0;}save();}else if(now-start>=60000){play=false;win=false;lose=true;save();}}
  void shoot(E e){float qx=px-e.x,qy=py-e.y,d=(float)Math.hypot(qx,qy);if(d>0)bs.add(new B(e.x,e.y,qx/d*6,qy/d*6,false,false,0));}
  void start(int l){level=Math.max(1,Math.min(open,l));play=true;menu=shop=levels=win=lose=false;php=hp[sel];px=getWidth()/2f;py=getHeight()/2f;vx=vy=0;spawn=dead=0;es.clear();bs.clear();cs.clear();long n=System.currentTimeMillis();start=lastFire=n;lastSpawn=n-1800;lastCrate=n;jx=105;jy=getHeight()-90;kx=jx;ky=jy;ax=getWidth()-105;ay=getHeight()-90;akx=ax;aky=ay;mt=at=false;bigUntil=0;}
  void result(Canvas c,int w,int h){txt(c,win?"THẮNG!":"THUA!",w/2,h/2-25,48,win?Color.GREEN:Color.RED,true,true);if(win)txt(c,"+100 xu   Thắng "+wins+"/2",w/2,h/2+15,18,Color.WHITE,true,true);btn(c,w/2-125,h/2+45,w/2+125,h/2+95,win&&level==15?"VỀ MENU":"CHƠI LẠI");}
  public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();int a=e.getActionMasked();if(!play&&a==1){if(win||lose){if(inside(x,y,getWidth()/2-130,getHeight()/2+35,getWidth()/2+130,getHeight()/2+110)){if(win&&level==15){win=lose=false;menu=true;}else{win=lose=false;start(level);}}}else if(shop)shopTap(x,y);else if(levels)levTap(x,y);else menuTap(x,y);return true;}if(play){if(a==0){if(x<getWidth()/2&&y>getHeight()-170){mt=true;setM(x,y);}else if(x>=getWidth()/2&&y>getHeight()-170){at=true;setA(x,y);}}else if(a==2){if(mt)setM(x,y);if(at)setA(x,y);}else if(a==1){mt=at=false;vx*=.7;vy*=.7;}}return true;}
  void setM(float x,float y){float qx=x-jx,qy=y-jy,d=(float)Math.hypot(qx,qy);if(d>60){qx*=60/d;qy*=60/d;}kx=jx+qx;ky=jy+qy;}void setA(float x,float y){float qx=x-ax,qy=y-ay,d=(float)Math.hypot(qx,qy);if(d>60){qx*=60/d;qy*=60/d;}akx=ax+qx;aky=ay+qy;}
  void menuTap(float x,float y){float w=getWidth();if(inside(x,y,w/2-150,150,w/2+150,205))start(level);else if(inside(x,y,w/2-150,220,w/2+150,275)){menu=false;levels=true;}else if(inside(x,y,w/2-150,290,w/2+150,345)){menu=false;shop=true;}}
  void shopTap(float x,float y){int h=getHeight();if(inside(x,y,20,h-52,145,h-12)){shop=false;menu=true;return;}for(int i=0;i<4;i++){float q=100+i*180;if(inside(x,y,q-65,262,q+65,310)){if(owned>=i)sel=i;else if(i==owned+1&&coins>=cost[i]){coins-=cost[i];owned=i;sel=i;}save();}}}
  void levTap(float x,float y){int h=getHeight();if(inside(x,y,20,h-52,145,h-12)){levels=false;menu=true;return;}for(int i=1;i<=15;i++){int z=i-1;float q=100+(z%5)*155,cy=75+(z/5)*82;if(inside(x,y,q-48,cy,q+48,cy+48)&&i<=open){level=i;levels=false;menu=true;return;}}}
  void btn(Canvas c,float l,float t,float rr,float b,String s){p.setColor(Color.rgb(42,55,45));c.drawRoundRect(l+2,t+2,rr+2,b+2,10,10,p);p.setColor(Color.rgb(75,112,78));c.drawRoundRect(l,t,rr,b,10,10,p);p.setStyle(Paint.Style.STROKE);p.setColor(Color.WHITE);p.setStrokeWidth(2);c.drawRoundRect(l,t,rr,b,10,10,p);p.setStyle(Paint.Style.FILL);txt(c,s,(l+rr)/2,(t+b)/2+6,16,Color.WHITE,true,true);}
  void txt(Canvas c,String s,float x,float y,float z,int col,boolean b,boolean cent){p.setTextSize(z);p.setColor(col);p.setTypeface(b?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);p.setTextAlign(cent?Paint.Align.CENTER:Paint.Align.LEFT);c.drawText(s,x,y,p);}void txtL(Canvas c,String s,float x,float y,float z,int col){txt(c,s,x,y,z,col,true,false);}void txtR(Canvas c,String s,float x,float y,float z,int col){p.setTextSize(z);p.setColor(col);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextAlign(Paint.Align.RIGHT);c.drawText(s,x,y,p);}static boolean inside(float x,float y,float l,float t,float rr,float b){return x>=l&&x<=rr&&y>=t&&y<=b;}static float distance(float a,float b,float c,float d){return (float)Math.hypot(a-c,b-d);}
  static class E{float x,y,sp;int hp,max;long lastShot;boolean boss;}static class B{float x,y,vx,vy;boolean player,big;int damage;B(float a,float b,float c,float d,boolean e,boolean f,int g){x=a;y=b;vx=c;vy=d;player=e;big=f;damage=g;}}static class C{float x,y;int type;}
 }
}
