package com.alpvz.gardendefense;
import android.app.*;import android.os.*;import android.content.pm.*;import android.graphics.*;import android.media.*;import android.view.*;import java.util.*;
public class MainActivity extends Activity{
GameView game;SoundPool sp;int shootS;MediaPlayer pfPlayer;boolean pfPlaying;
@Override public void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);getWindow().getDecorView().setSystemUiVisibility(5894);setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);initSound();game=new GameView();setContentView(game);}
void initSound(){AudioAttributes a=new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_GAME).setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION).build();sp=new SoundPool.Builder().setAudioAttributes(a).setMaxStreams(12).build();shootS=sp.load(this,R.raw.peashoot,1);}
void shootSound(){if(!pfPlaying&&sp!=null)sp.play(shootS,1,1,1,0,1);}
void pfSound(){if(pfPlaying)return;pfPlaying=true;if(pfPlayer!=null)pfPlayer.release();pfPlayer=MediaPlayer.create(this,R.raw.peashootplantfood);if(pfPlayer==null){pfPlaying=false;return;}pfPlayer.setOnCompletionListener(new MediaPlayer.OnCompletionListener(){public void onCompletion(MediaPlayer m){pfPlaying=false;m.release();pfPlayer=null;}});pfPlayer.start();}
@Override protected void onDestroy(){if(sp!=null)sp.release();if(pfPlayer!=null)pfPlayer.release();super.onDestroy();}
@Override public void onBackPressed(){if(game.screen==game.PLAY||game.screen==game.PAUSE)game.screen=game.PAUSE;else if(game.screen!=game.HOME)game.screen=game.HOME;else super.onBackPressed();game.invalidate();}
class GameView extends View{
static final int ROWS=5,COLS=9,LEVELS=9,SUNFLOWER=1,PEASHOOTER=2,GIGANUT=3,CHOMPER=4,REPEATER=5,MINE=6,NONE=0,SHOVEL=100,PF_TOOL=101,HOME=0,LEVELS_SCREEN=1,PLAY=2,PAUSE=3,WIN=4,LOSE=5;
Paint p=new Paint(1),t=new Paint(1);Random rnd=new Random();Plant[][] plants=new Plant[ROWS][COLS];ArrayList<Zombie> zombies=new ArrayList<>();ArrayList<Pea> peas=new ArrayList<>();ArrayList<SunDrop> suns=new ArrayList<>();Mower[] mowers=new Mower[ROWS];
Bitmap sunImg,peaImg,gigaImg,chompImg,repeatImg,mineImg,zombieImg,bulletImg;
int screen=HOME,level=1,unlocked=1,selected=PEASHOOTER,tool=NONE,sun=500,coins=99999,plantFood=3,wave=0,totalWaves=5,spawned=0,target=5;long lastFrame=System.currentTimeMillis(),lastSpawn,lastSun;float left,top,cw,ch;String msg="";long msgUntil;
GameView(){super(MainActivity.this);setFocusable(true);loadImages();for(int r=0;r<ROWS;r++)mowers[r]=new Mower(r);}
void loadImages(){sunImg=load("sun");peaImg=load("peashoot");gigaImg=load("giganut");chompImg=load("chomper");repeatImg=load("repeater");mineImg=load("min");zombieImg=load("zomplatz");bulletImg=load("gigapea");}
Bitmap load(String n){int id=getResources().getIdentifier(n,"drawable",getPackageName());return id==0?null:BitmapFactory.decodeResource(getResources(),id);}
@Override protected void onSizeChanged(int w,int h,int ow,int oh){left=w*.18f;top=h*.19f;cw=w*.073f;ch=h*.125f;}
@Override protected void onDraw(Canvas c){if(screen==HOME){home(c);return;}if(screen==LEVELS_SCREEN){levels(c);return;}gameDraw(c);if(screen==PAUSE)pause(c);if(screen==WIN)win(c);if(screen==LOSE)lose(c);if(screen==PLAY){update();postInvalidateDelayed(30);}}
void home(Canvas c){c.drawColor(Color.rgb(25,55,30));title(c,"GARDEN DEFENSE",.20f);button(c,.32f,.38f,.68f,.50f,"CHƠI");button(c,.32f,.55f,.68f,.67f,"CHỌN MÀN");small(c,"5×9 • 9 MÀN • MÁY CẮT CỎ",.82f,Color.LTGRAY);}
void levels(Canvas c){c.drawColor(Color.rgb(20,50,25));title(c,"CHỌN MÀN",.10f);for(int i=1;i<=LEVELS;i++){int cc=(i-1)%3,rr=(i-1)/3;float x=.18f+cc*.22f,y=.18f+rr*.20f;p.setColor(i<=unlocked?Color.rgb(65,145,70):Color.DKGRAY);c.drawRoundRect(getWidth()*x,getHeight()*y,getWidth()*(x+.17f),getHeight()*(y+.13f),18,18,p);center(c,i<=unlocked?"MÀN "+i:"KHÓA",getWidth()*(x+.085f),getHeight()*(y+.083f),getHeight()*.038f,Color.WHITE);}button(c,.04f,.83f,.20f,.94f,"QUAY LẠI");}
void gameDraw(Canvas c){c.drawColor(Color.rgb(92,155,70));p.setColor(Color.rgb(38,78,40));c.drawRect(0,0,getWidth(),top,p);smallAt(c,"☀ "+sun,12,getHeight()*.045f,Color.YELLOW);smallAt(c,"Màn "+level,getWidth()*.34f,getHeight()*.045f,Color.WHITE);smallAt(c,"Sóng "+wave+"/"+totalWaves,getWidth()*.46f,getHeight()*.045f,Color.WHITE);smallAt(c,"Xu "+coins,getWidth()*.70f,getHeight()*.045f,Color.YELLOW);smallAt(c,"PF "+plantFood,getWidth()*.87f,getHeight()*.045f,Color.WHITE);button(c,.76f,.075f,.91f,.145f,"MUA PF 100");if(System.currentTimeMillis()<msgUntil)center(c,msg,getWidth()*.72f,getHeight()*.16f,getHeight()*.035f,Color.YELLOW);cards(c);board(c);mowers(c);drawPlants(c);drawZombies(c);drawPeas(c);drawSuns(c);}
void cards(Canvas c){int[] a={SUNFLOWER,PEASHOOTER,GIGANUT,CHOMPER,REPEATER,MINE};for(int i=0;i<6;i++){float x=getWidth()*.01f+i*getWidth()*.075f,y=getHeight()*.075f,w=getWidth()*.065f,h=getHeight()*.09f;p.setColor(selected==a[i]&&tool==NONE?Color.YELLOW:Color.rgb(45,80,45));c.drawRoundRect(x,y,x+w,y+h,10,10,p);if(plantUnlocked(a[i]))drawPlant(c,a[i],x+w/2,y+h/2,Math.min(w,h)*.62f);else center(c,"🔒",x+w/2,y+h*.63f,h*.35f,Color.GRAY);}float x=getWidth()*.465f,y=getHeight()*.075f;p.setColor(tool==SHOVEL?Color.YELLOW:Color.DKGRAY);c.drawRoundRect(x,y,x+getWidth()*.065f,y+getHeight()*.09f,10,10,p);center(c,"X",x+getWidth()*.0325f,y+getHeight()*.06f,getHeight()*.035f,Color.WHITE);x=getWidth()*.54f;p.setColor(tool==PF_TOOL?Color.YELLOW:Color.rgb(90,45,125));c.drawRoundRect(x,y,x+getWidth()*.09f,y+getHeight()*.09f,10,10,p);center(c,"PF "+plantFood,x+getWidth()*.045f,y+getHeight()*.06f,getHeight()*.025f,Color.WHITE);}
void board(Canvas c){for(int r=0;r<ROWS;r++)for(int j=0;j<COLS;j++){p.setColor((r+j)%2==0?Color.rgb(103,166,78):Color.rgb(91,153,67));c.drawRect(left+j*cw,top+r*ch,left+(j+1)*cw,top+(r+1)*ch,p);}p.setColor(Color.rgb(130,92,52));c.drawRect(0,top,left,top+ROWS*ch,p);}
void drawPlants(Canvas c){for(int r=0;r<ROWS;r++)for(int j=0;j<COLS;j++){Plant a=plants[r][j];if(a==null)continue;float x=left+j*cw+cw/2,y=top+r*ch+ch/2;drawPlant(c,a.type,x,y,Math.min(cw,ch)*.72f);hp(c,x-cw*.30f,y+ch*.33f,cw*.60f,5,a.hp,a.maxHp);}}
void drawPlant(Canvas c,int type,float x,float y,float s){Bitmap b=img(type);if(b!=null){c.drawBitmap(b,null,new RectF(x-s*.48f,y-s*.48f,x+s*.48f,y+s*.48f),p);return;}p.setColor(type==SUNFLOWER?Color.YELLOW:type==GIGANUT?Color.rgb(155,105,55):type==CHOMPER?Color.rgb(145,80,185):Color.rgb(55,175,70);c.drawCircle(x,y,s*.38f,p);}
Bitmap img(int type){if(type==SUNFLOWER)return sunImg;if(type==PEASHOOTER)return peaImg;if(type==GIGANUT)return gigaImg;if(type==CHOMPER)return chompImg;if(type==REPEATER)return repeatImg;return mineImg;}
void drawZombies(Canvas c){for(Zombie z:zombies){float w=z.boss?cw*1.18f:cw*.60f,h=z.boss?ch*1.15f:ch*.78f;if(zombieImg!=null)c.drawBitmap(zombieImg,null,new RectF(z.x-w/2,z.y-h*.1f,z.x+w/2,z.y+h*.9f),p);else{p.setColor(z.boss?Color.rgb(95,40,110):Color.GRAY);c.drawOval(new RectF(z.x-w/2,z.y-h*.1f,z.x+w/2,z.y+h*.9f),p);}hp(c,z.x-w/2,z.y-h*.2f,w,5,z.hp,z.maxHp);}}
void drawPeas(Canvas c){for(Pea q:peas){float s=q.big?22:10;if(bulletImg!=null)c.drawBitmap(bulletImg,null,new RectF(q.x-s,q.y-s,q.x+s,q.y+s),p);else{p.setColor(q.big?Color.rgb(80,255,80):Color.GREEN);c.drawCircle(q.x,q.y,q.big?15:7,p);}}}
void drawSuns(Canvas c){for(SunDrop s:suns){p.setColor(Color.YELLOW);c.drawCircle(s.x,s.y,16,p);center(c,"+",s.x,s.y+5,15,Color.rgb(120,80,0));}}
void mowers(Canvas c){for(Mower m:mowers){float y=top+m.row*ch+ch*.70f;p.setColor(m.used?Color.DKGRAY:Color.rgb(180,70,40));c.drawRoundRect(m.x-cw*.30f,y-ch*.23f,m.x+cw*.30f,y+ch*.02f,7,7,p);p.setColor(Color.BLACK);c.drawCircle(m.x-cw*.18f,y+5,7,p);c.drawCircle(m.x+cw*.18f,y+5,7,p);}}void update(){long now=System.currentTimeMillis();float dt=Math.min(.05f,(now-lastFrame)/1000f);lastFrame=now;if(now-lastSun>8000){lastSun=now;suns.add(new SunDrop(left+rnd.nextInt(COLS)*cw+cw/2,top*.80f));}updatePlants(now);updatePeas(dt);updateZombies(now,dt);updateMowers(dt);removeDead();if(spawned<target&&now-lastSpawn>=spawnDelay()){spawnZombie();spawned++;lastSpawn=now;}if(spawned>=target&&zombies.isEmpty()){wave++;if(wave>=totalWaves)winLevel();else{spawned=0;target=waveTarget();lastSpawn=now;}}}
void updatePlants(long now){for(int r=0;r<ROWS;r++)for(int j=0;j<COLS;j++){Plant a=plants[r][j];if(a==null)continue;boolean pf=a.pfUntil>now;long cd=pf?100:1500;if(a.type==SUNFLOWER&&now-a.lastAction>=(pf?100:7000)){suns.add(new SunDrop(left+j*cw+cw/2,top+r*ch+ch*.25f));a.lastAction=now;}if(a.type==PEASHOOTER&&now-a.lastAction>=cd&&rowHasZombie(r)){fire(r,j,30,false);a.lastAction=now;}if(a.type==REPEATER){if(now-a.lastAction>=(pf?100:1800)&&rowHasZombie(r)){fire(r,j,28,false);a.secondShotAt=now+100;a.lastAction=now;a.bigPending=true;}if(a.secondShotAt>0&&now>=a.secondShotAt){fire(r,j,28,false);a.secondShotAt=0;if(a.bigPending){fire(r,j,1000,true);a.bigPending=false;}}}if(a.type==CHOMPER&&now-a.lastAction>=3500){Zombie z=near(r,j);if(z!=null){z.hp=0;a.lastAction=now;}}if(a.type==MINE&&now>=a.armedAt){Zombie z=cellZombie(r,j);if(z!=null){z.hp=0;a.hp=0;}}}}
void fire(int r,int j,int damage,boolean big){peas.add(new Pea(left+j*cw+cw*.55f,top+r*ch+ch*.50f,r,damage,big,false,1));if(!big)shootSound();}
void updatePeas(float dt){ArrayList<Pea> add=new ArrayList<>();Iterator<Pea>it=peas.iterator();long now=System.currentTimeMillis();while(it.hasNext()){Pea q=it.next();q.x+=q.dir*cw*9f*dt;if(q.fromZombie){Plant hit=null;for(int j=0;j<COLS;j++){Plant a=plants[q.row][j];if(a!=null&&Math.abs(left+j*cw+cw/2-q.x)<cw*.30f){hit=a;break;}}if(hit!=null){hit.hp-=q.damage;it.remove();}else if(q.x<left-cw)it.remove();continue;}Zombie caught=null;for(Zombie z:zombies)if(z.boss&&z.row==q.row&&Math.abs(z.x-q.x)<(q.big?cw*.42f:cw*.28f)&&now>=z.catchReadyAt){caught=z;break;}if(caught!=null){caught.catchReadyAt=now+5000;it.remove();add.add(new Pea(caught.x-cw*.35f,caught.y+ch*.35f,caught.row,500,false,true,-1));continue;}Zombie hit=null;for(Zombie z:zombies)if(z.row==q.row&&Math.abs(z.x-q.x)<(q.big?cw*.42f:cw*.28f)){hit=z;break;}if(hit!=null){hit.hp-=q.damage;it.remove();}else if(q.x>getWidth()+30)it.remove();}peas.addAll(add);}
void updateZombies(long now,float dt){for(Zombie z:zombies){if(z.hp<=0)continue;if(z.boss){z.x+=z.dir*cw*1.4f*dt;float mn=left+cw*2,mx=getWidth()-cw;if(z.x<mn){z.x=mn;z.dir=1;}if(z.x>mx){z.x=mx;z.dir=-1;}}else{Plant a=plantAt(z);if(a!=null){if(now-z.lastAttack>=800){a.hp-=z.damage;z.lastAttack=now;}}else z.x-=Math.min(z.speed,getWidth()*.035f)*dt;}if(!z.boss&&z.x<left-cw*.4f){Mower m=mowers[z.row];if(!m.used){m.used=true;m.active=true;m.x=left-cw*.5f;}else{screen=LOSE;return;}}}}
void updateMowers(float dt){for(Mower m:mowers)if(m.active){m.x+=cw*18f*dt;for(Zombie z:zombies)if(z.row==m.row&&Math.abs(z.x-m.x)<cw*.55f)z.hp=0;if(m.x>getWidth()+cw)m.active=false;}}
void spawnZombie(){int r=rnd.nextInt(ROWS);boolean boss=level==9&&wave==totalWaves-1&&spawned==target-1;zombies.add(new Zombie(r,rnd.nextInt(3),boss));}
void removeDead(){Iterator<Zombie>it=zombies.iterator();while(it.hasNext()){Zombie z=it.next();if(z.hp<=0){it.remove();coins+=z.boss?100:5;}}for(int r=0;r<ROWS;r++)for(int j=0;j<COLS;j++)if(plants[r][j]!=null&&plants[r][j].hp<=0)plants[r][j]=null;}
boolean rowHasZombie(int r){for(Zombie z:zombies)if(z.row==r&&z.x>left)return true;return false;}
Plant plantAt(Zombie z){int j=(int)((z.x-left)/cw);return j<0||j>=COLS?null:plants[z.row][j];}
Zombie cellZombie(int r,int j){float x=left+j*cw+cw/2;for(Zombie z:zombies)if(z.row==r&&Math.abs(z.x-x)<cw*.45f)return z;return null;}
Zombie near(int r,int j){float x=left+j*cw+cw/2;Zombie best=null;float d0=99999;for(Zombie z:zombies)if(z.row==r){float d=Math.abs(z.x-x);if(d<cw*1.4f&&d<d0){best=z;d0=d;}}return best;}
void startLevel(int lv){level=Math.max(1,Math.min(LEVELS,lv));screen=PLAY;clear();wave=0;spawned=0;target=waveTarget();totalWaves=wavesForLevel();lastSpawn=System.currentTimeMillis();lastSun=lastSpawn;lastFrame=lastSpawn;}
void clear(){for(int r=0;r<ROWS;r++){for(int j=0;j<COLS;j++)plants[r][j]=null;mowers[r]=new Mower(r);}zombies.clear();peas.clear();suns.clear();selected=PEASHOOTER;tool=NONE;}
int wavesForLevel(){return level<=2?5:level<=4?6:level<=8?5:7;}
int waveTarget(){return 3+Math.min(5,level/2+wave);}
long spawnDelay(){return level<=2?4300:level<=4?3800:level<=8?3200:2600;}
boolean plantUnlocked(int type){if(type==PEASHOOTER)return level>=1;if(type==SUNFLOWER)return level>=1;if(type==GIGANUT)return level>=2;if(type==MINE)return level>=3;if(type==CHOMPER)return level>=4;if(type==REPEATER)return level>=5;return false;}
int cost(int type){return type==SUNFLOWER?50:type==PEASHOOTER?100:type==GIGANUT?125:type==CHOMPER?150:type==REPEATER?200:50;}
int mowerReward(){int n=0;for(Mower m:mowers)if(!m.used)n+=50;return n;}
void winLevel(){screen=WIN;coins+=mowerReward();if(level<LEVELS)unlocked=Math.max(unlocked,level+1);}void pause(Canvas c){overlay(c,Color.argb(190,0,0,0));title(c,"TẠM DỪNG",.34f);button(c,.32f,.50f,.68f,.63f,"TIẾP TỤC");}
void win(Canvas c){overlay(c,Color.argb(215,0,80,0));title(c,"CHIẾN THẮNG!",.32f);button(c,.30f,.55f,.70f,.68f,level<LEVELS?"MÀN TIẾP":"MENU");}
void lose(Canvas c){overlay(c,Color.argb(220,100,0,0));title(c,"THUA!",.32f);button(c,.30f,.50f,.70f,.63f,"CHƠI LẠI");button(c,.30f,.68f,.70f,.81f,"MENU");}
void hp(Canvas c,float x,float y,float w,float h,float v,float max){p.setColor(Color.RED);c.drawRect(x,y,x+w,y+h,p);p.setColor(Color.GREEN);c.drawRect(x,y,x+w*Math.max(0,Math.min(1,v/max)),y+h,p);}
void overlay(Canvas c,int col){p.setColor(col);c.drawRect(0,0,getWidth(),getHeight(),p);}
void title(Canvas c,String s,float y){center(c,s,getWidth()/2f,getHeight()*y,getHeight()*.07f,Color.WHITE);}
void small(Canvas c,String s,float y,int col){center(c,s,getWidth()/2f,getHeight()*y,getHeight()*.035f,col);}
void smallAt(Canvas c,String s,float x,float y,int col){t.setTextAlign(Paint.Align.LEFT);t.setTextSize(getHeight()*.033f);t.setColor(col);c.drawText(s,x,y,t);}
void center(Canvas c,String s,float x,float y,float size,int col){t.setTextAlign(Paint.Align.CENTER);t.setTextSize(size);t.setColor(col);c.drawText(s,x,y,t);}
void button(Canvas c,float x1,float y1,float x2,float y2,String s){p.setColor(Color.rgb(65,135,70));c.drawRoundRect(getWidth()*x1,getHeight()*y1,getWidth()*x2,getHeight()*y2,16,16,p);center(c,s,getWidth()*(x1+x2)/2,getHeight()*(y1+y2)/2+getHeight()*.02f,getHeight()*.038f,Color.WHITE);}
@Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY();if(screen==HOME){if(inside(x,y,.32f,.38f,.68f,.50f))startLevel(level);else if(inside(x,y,.32f,.55f,.68f,.67f))screen=LEVELS_SCREEN;invalidate();return true;}if(screen==LEVELS_SCREEN){if(inside(x,y,.04f,.83f,.20f,.94f)){screen=HOME;invalidate();return true;}for(int i=1;i<=LEVELS;i++){int cc=(i-1)%3,rr=(i-1)/3;float x1=.18f+cc*.22f,y1=.18f+rr*.20f;if(insidePx(x,y,getWidth()*x1,getHeight()*y1,getWidth()*(x1+.17f),getHeight()*(y1+.13f))&&i<=unlocked){startLevel(i);return true;}}return true;}if(screen==WIN){if(inside(x,y,.30f,.55f,.70f,.68f)){if(level<LEVELS)startLevel(level+1);else screen=HOME;invalidate();}return true;}if(screen==LOSE){if(inside(x,y,.30f,.50f,.70f,.63f))startLevel(level);else if(inside(x,y,.30f,.68f,.70f,.81f))screen=HOME;invalidate();return true;}if(screen==PAUSE){if(inside(x,y,.32f,.50f,.68f,.63f))screen=PLAY;invalidate();return true;}Iterator<SunDrop>si=suns.iterator();while(si.hasNext()){SunDrop s=si.next();if(Math.hypot(x-s.x,y-s.y)<Math.max(55,getHeight()*.065f)){sun+=25;si.remove();invalidate();return true;}}float cy=getHeight()*.075f,chh=getHeight()*.09f;if(y>=cy&&y<=cy+chh){int[] ids={SUNFLOWER,PEASHOOTER,GIGANUT,CHOMPER,REPEATER,MINE};for(int i=0;i<6;i++){float x1=getWidth()*.01f+i*getWidth()*.075f;if(x>=x1&&x<=x1+getWidth()*.065f){if(plantUnlocked(ids[i])){selected=ids[i];tool=NONE;}return true;}}float sx=getWidth()*.465f;if(x>=sx&&x<=sx+getWidth()*.065f){tool=SHOVEL;invalidate();return true;}float bx=getWidth()*.76f;if(x>=bx&&x<=getWidth()*.91f){if(coins>=100){coins-=100;plantFood++;msg="MUA PF -100 XU";}else msg="KHONG DU 100 XU";msgUntil=System.currentTimeMillis()+1000;invalidate();return true;}float fx=getWidth()*.54f;if(x>=fx&&x<=fx+getWidth()*.12f&&plantFood>0){tool=PF_TOOL;invalidate();return true;}}if(x>=left&&x<left+COLS*cw&&y>=top&&y<top+ROWS*ch){int j=(int)((x-left)/cw),r=(int)((y-top)/ch);if(tool==SHOVEL){plants[r][j]=null;tool=NONE;invalidate();return true;}if(tool==PF_TOOL){Plant a=plants[r][j];if(a!=null&&plantFood>0){usePF(a);plantFood--;}tool=NONE;invalidate();return true;}if(plants[r][j]==null&&plantUnlocked(selected)){int co=cost(selected);if(sun>=co){sun-=co;plants[r][j]=new Plant(selected,r,j);}}invalidate();return true;}return true;}
void usePF(Plant a){long n=System.currentTimeMillis();if(a.type==SUNFLOWER||a.type==PEASHOOTER||a.type==REPEATER){a.pfUntil=n+3000;a.lastAction=n-100;if(a.type==PEASHOOTER||a.type==REPEATER)pfSound();}else if(a.type==GIGANUT){a.maxHp=8000;a.hp=8000;}else if(a.type==CHOMPER){Zombie z=near(a.row,a.col);if(z!=null)z.hp=0;}else if(a.type==MINE){for(Zombie z:zombies)if(z.row==a.row&&Math.abs(z.x-(left+a.col*cw+cw/2))<cw*2)z.hp-=1800;a.hp=0;}}
boolean inside(float x,float y,float a,float b,float c,float d){return insidePx(x,y,getWidth()*a,getHeight()*b,getWidth()*c,getHeight()*d);}
boolean insidePx(float x,float y,float a,float b,float c,float d){return x>=a&&x<=c&&y>=b&&y<=d;}
class Plant{final int type,row,col;int maxHp,hp;long lastAction,secondShotAt,armedAt,pfUntil;boolean bigPending;Plant(int t,int r,int j){type=t;row=r;col=j;maxHp=t==GIGANUT?4000:t==MINE?120:500;hp=maxHp;long n=System.currentTimeMillis();lastAction=n;armedAt=t==MINE?n+3000:Long.MAX_VALUE;}}
class Zombie{float x,y,speed,dir=-1,hp,maxHp;final int row,type;final boolean boss;int damage;long lastAttack,catchReadyAt;Zombie(int r,int ty,boolean b){row=r;type=ty;boss=b;x=left+COLS*cw+cw;y=top+r*ch+ch*.16f;if(b){maxHp=5000;speed=cw*.10f;damage=45;}else if(ty==1){maxHp=1000+level*100;speed=cw*.13f;damage=32;}else if(ty==2){maxHp=450+level*60;speed=cw*.32f;damage=18;}else{maxHp=650+level*75;speed=cw*.20f;damage=24;}hp=maxHp;catchReadyAt=System.currentTimeMillis()+5000;}}
class Pea{float x;final float y;final int row,damage,dir;final boolean big,fromZombie;Pea(float X,float Y,int r,int d,boolean b,boolean f,int di){x=X;y=Y;row=r;damage=d;big=b;fromZombie=f;dir=di;}}
class SunDrop{final float x,y;SunDrop(float X,float Y){x=X;y=Y;}}
class Mower{final int row;float x;boolean used,active;Mower(int r){row=r;x=left-cw*.5f;}}
}
    }
